language: java
sudo: true
install: true

addons:
  sonarqube:
    organization: "christian-draeger-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

before_script:
  - pip install --user codecov

after_success:
  - codecov

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
