language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "sonarsource"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
